language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t kentasato/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true kentasato/docker-react npm run test -- --coverage
  
deploy:
  provider: elasticbeanstalk
  region: "ap-northeast-1"
  app: "docker-react"
  env: "DockerReact-env"
  bucket_name: "elasticbeanstalk-ap-northeast-1-376773732514"
  bucket_path: "docker-react"
    on:
      breanch: master
  access_key_id:
    secure: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"
