language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t kentasato/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true kentasato/docker-react npm run test -- --coverage

